# Starship
eval "$(starship init zsh)"

# Clear dulu biar clean
clear

# Neofetch hacker style
neofetch --ascii_distro kali

# Efek ketik
echo -e "\e[1;32m[✔] System Initialized...\e[0m"
echo -e "\e[1;36m[✔] Welcome, $(whoami)\e[0m"
echo ""

# Alias
alias cls="clear"
alias ll="ls -la --color=auto"
alias hack="cmatrix"