add_newline = true

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[directory]
style = "cyan bold"

[git_branch]
symbol = "🌱 "
style = "purple"

[username]
style_user = "blue bold"
show_always = true