add_newline = true

format = """
[┌─](bold green)$username$hostname$directory$git_branch
[└─➤](bold green) """

[username]
style_user = "bold green"
show_always = true

[hostname]
style = "bold green"
ssh_only = false

[directory]
style = "bold cyan"

[git_branch]
symbol = " "
style = "bold purple"

[character]
success_symbol = "[➤](bold green)"
error_symbol = "[✖](bold red)"